name: oams

services:
  apiserver:
    image: oamsstaging.azurecr.io/apiserver
    container_name: apiserver
    build:
      context: .
      dockerfile: ./cmd/apiserver/Dockerfile
      secrets:
        - ssh_key
    ports:
      - "3001:3001"
    network_mode: bridge

  webserver:
    image: oamsstaging.azurecr.io/webserver
    container_name: webserver
    build:
      context: ../frontend
      dockerfile: ../backend/cmd/webserver/Dockerfile
      secrets:
        - env
    ports:
      - "3000:3000"
    network_mode: bridge

secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
  env:
    file: ../frontend/.env.production
