version: "2"
sql:
  - engine: "postgresql"
    queries: [
      "users.sql",
      "classes.sql",
      "class_groups.sql",
      "class_group_sessions.sql",
      "session_enrollments.sql",
    ]
    schema: "migrations/"
    gen:
      go:
        package: "database"
        sql_package: "pgx/v5"
        out: "../"
        emit_json_tags: true