version: "2"
sql:
  - engine: "postgresql"
    queries: ["query.sql", "users.sql"]
    schema: "migrations/"
    gen:
      go:
        package: "database"
        sql_package: "pgx/v5"
        out: "../"
        emit_json_tags: true