// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertClassGroupSessions = `-- name: UpsertClassGroupSessions :batchone
INSERT INTO class_group_sessions (class_group_id, start_time, end_time, venue, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT ON CONSTRAINT ux_class_group_id_start_time
    DO UPDATE SET end_time   = $3,
                  venue      = $4,
                  updated_at =
                      CASE
                          WHEN $3 <> class_group_sessions.end_time OR
                               $4 <> class_group_sessions.venue
                              THEN NOW()
                          ELSE class_group_sessions.updated_at
                          END
RETURNING id, class_group_id, start_time, end_time, venue, created_at, updated_at
`

type UpsertClassGroupSessionsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClassGroupSessionsParams struct {
	ClassGroupID int64              `json:"class_group_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Venue        string             `json:"venue"`
}

// Insert a class group session into the database. If the class group session already exists, only update
// the end_time and venue.
func (q *Queries) UpsertClassGroupSessions(ctx context.Context, arg []UpsertClassGroupSessionsParams) *UpsertClassGroupSessionsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ClassGroupID,
			a.StartTime,
			a.EndTime,
			a.Venue,
		}
		batch.Queue(upsertClassGroupSessions, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClassGroupSessionsBatchResults{br, len(arg), false}
}

func (b *UpsertClassGroupSessionsBatchResults) QueryRow(f func(int, ClassGroupSession, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i ClassGroupSession
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.ClassGroupID,
			&i.StartTime,
			&i.EndTime,
			&i.Venue,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertClassGroupSessionsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertClassGroups = `-- name: UpsertClassGroups :batchone
INSERT INTO class_groups (class_id, name, class_type, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT DO NOTHING
RETURNING id, class_id, name, class_type, created_at, updated_at
`

type UpsertClassGroupsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClassGroupsParams struct {
	ClassID   int64     `json:"class_id"`
	Name      string    `json:"name"`
	ClassType ClassType `json:"class_type"`
}

// Insert a class group into the database. If the class group already exists, do nothing.
func (q *Queries) UpsertClassGroups(ctx context.Context, arg []UpsertClassGroupsParams) *UpsertClassGroupsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ClassID,
			a.Name,
			a.ClassType,
		}
		batch.Queue(upsertClassGroups, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClassGroupsBatchResults{br, len(arg), false}
}

func (b *UpsertClassGroupsBatchResults) QueryRow(f func(int, ClassGroup, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i ClassGroup
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.ClassID,
			&i.Name,
			&i.ClassType,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertClassGroupsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertClasses = `-- name: UpsertClasses :batchone
INSERT INTO classes (code, year, semester, programme, au, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT
    ON CONSTRAINT ux_code_year_semester
    DO UPDATE SET programme  = $4,
                  au         = $5,
                  updated_at =
                      CASE
                          WHEN $4 <> classes.programme OR
                               $5 <> classes.au
                              THEN NOW()
                          ELSE classes.updated_at
                          END
RETURNING id, code, year, semester, programme, au, created_at, updated_at
`

type UpsertClassesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClassesParams struct {
	Code      string `json:"code"`
	Year      int32  `json:"year"`
	Semester  string `json:"semester"`
	Programme string `json:"programme"`
	Au        int16  `json:"au"`
}

// Insert a class into the database. If the class already exists, then only update the programme and au.
func (q *Queries) UpsertClasses(ctx context.Context, arg []UpsertClassesParams) *UpsertClassesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Code,
			a.Year,
			a.Semester,
			a.Programme,
			a.Au,
		}
		batch.Queue(upsertClasses, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClassesBatchResults{br, len(arg), false}
}

func (b *UpsertClassesBatchResults) QueryRow(f func(int, Class, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Class
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Code,
			&i.Year,
			&i.Semester,
			&i.Programme,
			&i.Au,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertClassesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertSessionEnrollments = `-- name: UpsertSessionEnrollments :batchone
INSERT INTO session_enrollments (session_id, user_id, attended, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT DO NOTHING
RETURNING id, session_id, user_id, attended, created_at, updated_at
`

type UpsertSessionEnrollmentsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertSessionEnrollmentsParams struct {
	SessionID int64  `json:"session_id"`
	UserID    string `json:"user_id"`
	Attended  bool   `json:"attended"`
}

// Insert a session enrollment into the database. If the session enrollment already exists, do nothing.
func (q *Queries) UpsertSessionEnrollments(ctx context.Context, arg []UpsertSessionEnrollmentsParams) *UpsertSessionEnrollmentsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SessionID,
			a.UserID,
			a.Attended,
		}
		batch.Queue(upsertSessionEnrollments, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertSessionEnrollmentsBatchResults{br, len(arg), false}
}

func (b *UpsertSessionEnrollmentsBatchResults) QueryRow(f func(int, SessionEnrollment, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i SessionEnrollment
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Attended,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertSessionEnrollmentsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertUsers = `-- name: UpsertUsers :batchone
INSERT INTO users (id, name, email, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (id)
    DO UPDATE SET name       = $2,
                  email      = $3,
                  updated_at =
                      CASE
                          WHEN $2 <> users.name OR
                               $3 <> users.email OR
                               $4 <> users.role
                              THEN NOW()
                          ELSE users.updated_at
                          END
RETURNING id, name, email, role, created_at, updated_at
`

type UpsertUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertUsersParams struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Email string   `json:"email"`
	Role  UserRole `json:"role"`
}

// Insert a user into the database. If the user already exists, then only update the name and email.
func (q *Queries) UpsertUsers(ctx context.Context, arg []UpsertUsersParams) *UpsertUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Name,
			a.Email,
			a.Role,
		}
		batch.Queue(upsertUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertUsersBatchResults{br, len(arg), false}
}

func (b *UpsertUsersBatchResults) QueryRow(f func(int, User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
