// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"
)

type Professor struct {
	ID    int64
	Name  string
	Email sql.NullString
}

type Student struct {
	MatricNo string
	Name     string
	Email    sql.NullString
}
