package common

import (
	"time"

	"github.com/darylhjd/oams/backend/internal/database"
)

// ClassCreationData is a struct containing data for creating a class. It is used by both file and JSON requests
// for class creation.
type ClassCreationData struct {
	// Filename and FileCreationDate is specific to creation data generated by file upload.
	Filename         string    `json:"filename"`
	FileCreationDate time.Time `json:"file_creation_date"`

	Course      database.CreateCoursesParams `json:"course"`
	ClassGroups []ClassGroupData             `json:"class_groups"`

	// Error provides an explanation for any failures while processing the creation data.
	Error string `json:"error"`

	// These private variables are helper fields for generating filled data.
	classType database.ClassType
}

// IsValid is a helper function to check if a ClassCreationData is valid for data processing.
func (c ClassCreationData) IsValid() bool {
	return c.Error == ""
}

// ClassGroupData is a struct containing data for creating a class group and its associated sessions.
type ClassGroupData struct {
	database.CreateClassGroupsParams
	Sessions []database.CreateClassGroupSessionsParams `json:"sessions"`
	Students []database.CreateStudentsParams           `json:"students"`
}
