package common

import (
	"fmt"
	"time"

	"github.com/darylhjd/oams/backend/internal/database"
)

// ClassCreationData is a struct containing data for creating a class. It is used by both file and JSON requests
// for class creation. Prior to processing the data here, the caller should call IsValid on the data at least once.
type ClassCreationData struct {
	// Filename and FileCreationDate is specific to creation data generated by file upload.
	Filename         string    `json:"filename"`
	FileCreationDate time.Time `json:"file_creation_date"`

	Course      database.UpsertCoursesParams `json:"course"`
	ClassGroups []ClassGroupData             `json:"class_groups"`

	// These variables are helper fields for generating filled data.
	ClassType database.ClassType `json:"-"`
}

// ClassGroupData is a struct containing data for creating a class group and its associated sessions.
type ClassGroupData struct {
	database.UpsertClassGroupsParams
	Sessions []SessionData                   `json:"sessions"`
	Students []database.UpsertStudentsParams `json:"students"`
}

type SessionData struct {
	Course *ClassCreationData `json:"-"`
	database.UpsertClassGroupSessionsParams
}

// IsValid is a helper function to check if a ClassCreationData is valid and returns an error if it is not.
func (c *ClassCreationData) IsValid() error {
	if len(c.ClassGroups) == 0 {
		return fmt.Errorf("%s - creation data has no valid class groups", namespace)
	}

	for _, classGroup := range c.ClassGroups {
		if len(classGroup.Sessions) == 0 {
			return fmt.Errorf("%s - class group %s has no sessions", namespace, classGroup.Name)
		}

		if len(classGroup.Students) == 0 {
			return fmt.Errorf("%s - class group %s has no enrollments", namespace, classGroup.Name)
		}
	}

	return nil
}
