# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Backend Test
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: "github.com/darylhjd/*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.work

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0

    - name: Configuration for private dependencies
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Install dependencies
      run: |
        cd backend  
        go get ./...

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Test
      run: |
        cd backend
        go test ./...