name: Frontend

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        env:
          AZURE_LOGIN_SCOPE: ${{ vars.AZURE_LOGIN_SCOPE }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
          API_SERVER: ${{ vars.API_SERVER }}
          WEB_SERVER: ${{ vars.WEB_SERVER }}
        run: |
          cd frontend
          npx next telemetry disable
          npm install
          npm run build
