# This workflow executes all tests in OAMS.

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        env:
          AZURE_LOGIN_SCOPE: ${{ vars.AZURE_LOGIN_SCOPE }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
          API_SERVER: ${{ vars.API_SERVER }}
          WEB_SERVER: ${{ vars.WEB_SERVER }}
        run: |
          cd frontend
          npx next telemetry disable
          npm install
          npm run build

  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2-bullseye
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: oams-tester
          POSTGRES_PASSWORD: oams-test
        ports:
          - 32769:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Configuration for private dependencies
        env:
          GOPRIVATE: "github.com/darylhjd/*"
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://darylhjd:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install Go dependencies
        run: |
          cd backend  
          go get ./...

      - name: Test backend
        env:
          APP_ENV: ${{ vars.APP_ENV }}
          API_SERVER_PORT: ${{ vars.API_SERVER_PORT }}
          API_SERVER_AZURE_TENANT_ID: ${{ vars.API_SERVER_AZURE_TENANT_ID }}
          API_SERVER_AZURE_CLIENT_ID: ${{ vars.API_SERVER_AZURE_CLIENT_ID }}
          WEB_SERVER: ${{ vars.WEB_SERVER }}
          DATABASE_TYPE: ${{ vars.DATABASE_TYPE }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          DATABASE_USER: ${{ vars.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ vars.DATABASE_HOST }}
          DATABASE_PORT: ${{ vars.DATABASE_PORT }}
          DATABASE_SSL_MODE: ${{ vars.DATABASE_SSL_MODE }}
        run: |
          cd backend
          go test ./...