# This workflow executes all tests in Oats.

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: "github.com/darylhjd/*"

jobs:
  test-all:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.work
          cache-dependency-path: backend/go.sum

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Configuration for private dependencies
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://darylhjd:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install Go dependencies
        run: |
          cd backend  
          go get ./...

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Test backend
        run: |
          cd backend
          go test ./...