# This workflow executes all tests in Oats.

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_ENV: ${{ vars.APP_ENV }}
  DATABASE_TYPE: ${{ vars.DATABASE_TYPE }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  DATABASE_USER: ${{ vars.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
  DATABASE_HOST: ${{ vars.DATABASE_HOST }}
  DATABASE_PORT: ${{ vars.DATABASE_PORT }}

jobs:
  test-all:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2-bullseye
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: $DATABASE_PASSWORD
        ports:
          - "$DATABASE_PORT":5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.work
          cache-dependency-path: backend/go.sum

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Configuration for private dependencies
        env:
          GOPRIVATE: "github.com/darylhjd/*"
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://darylhjd:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install Go dependencies
        run: |
          cd backend  
          go get ./...

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Test backend
        run: |
          cd backend
          go test ./...